
// if you're using pannel carefully edit this part.

const sessionName = 'session';
const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNlBhZHpSc0RUMDdrbnpHUWg2MnRDQW5BOXpLYkdjNnRxZHNpamdZTjBGMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicTlMOE1wUE1TR0x1bTd1Z2ZjVnBBMVhlVW5YcWorTXV5TFZocUZVRzNqMD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJHUFBiNVVYb1VvODVsYnQ2eFNwQXRTMElNT0ZMeFRVMmtqcUxxNkJiQjEwPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIyL0JHbEZSNDFuNlVLajEvM0ZwcE95TFFlL2NGcnQ4ampTaFN4TGd2VjJzPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IldIME5rWHo2MUVmNG1Qa0xDUTVBaUxSbDNqZzczalFrL3N0cXZOVC9TM1E9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkN6M2JqK01ZY1ZDL2xJK3NrTUNLWVFEOWN3ZVZwOU4xc0dON0xtc3NUMlE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSUJCUm5DMTJuNTVRREdpRnNHR1NuV205ZGlyZVZkcUdYMUsrdTNCcGlFST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic2cwWTNyY1Z5MFQ1MndUTFZTb3R5OEczalRsTS91cHRpN0Rpb0dReUpGZz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlN5TWZBN3lPRFY0ZGJFMFpnUXZYR3hiWU9PU2FHUmJoR282cUlDUGNyalRuenRzVWJ5cmpSbHlzcDFaMVFhalpVZDZKL0tnNTNReHBQNWFLbzdvOWdRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTA5LCJhZHZTZWNyZXRLZXkiOiJnZy9zc2JOVFZGUm80cVhJdXRleTIyOEJ2QzRMcnZzYVBwT2xUS1ExSmc4PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6ODEzLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6ODEzLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IlJBVkVOQk9UIiwibWUiOnsiaWQiOiIyNTQ3NTg0NDMxMTE6MTdAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIxMTc0ODA4Mjc2NTgyNTA6MTdAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNPK2tuYWNIRUpyUitja0dHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJ0MU56NFZvN0JFNG9HWkx2djN5VytWUmwrOVp6eStJNGVFZC9TcFMrRjJJPSIsImFjY291bnRTaWduYXR1cmUiOiJpbEV1enUvQm41eDZMdnRzV0o1VWRLTUFKOFdtdkhqRXJOWGx1SHhWcnV3SkxHMHVyVjFtWU5TcnBZdk81Tk5GblpMSzI1RVFQUUFOYXdOYW5objNDdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoicC9sYXM2Zi9XdVVHMmVJZWxtN0QvNHZHZ01KR0FQSmFFSnNkcUp1YXhMOFNZeDdJa05zVXJLREY0YlNQcGdSK292cG9JZnZTL1RhVEdPVlN0UmFLZ2c9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3NTg0NDMxMTE6MTdAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCYmRUYytGYU93Uk9LQm1TNzc5OGx2bFVaZnZXYzh2aU9IaEhmMHFVdmhkaSJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FVSURRZ0MifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzY1Njk3NzA1LCJsYXN0UHJvcEhhc2giOiIyVjc3cVUifQ==';
const appname = process.env.APP_NAME || '';
const herokuapi = process.env.HEROKU_API;
const botname = process.env.BOTNAME || '𝗥𝗔𝗩𝗘𝗡-𝗕𝗢𝗧';
const author = process.env.STICKER_AUTHOR || 'MŦΛṖƐĿĪ ᎳᎪ ᏦᎯᎽᎾℒℰ';
const packname = process.env.STICKER_PACKNAME || 'ΛĿĿƐИ';
const dev = process.env.DEV || '254758443111';
const owner = dev.split(",");
const bad = process.env.BAD_WORD || 'fuck,umbwa,kuma,pussy,slut,bitch,cock,stupid';
const admin = process.env.ADMIN_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗿𝗲𝘀𝗲𝗿𝘃𝗲𝗱 𝗳𝗼𝗿 𝗔𝗱𝗺𝗶𝗻𝘀!';
const group = process.env.GROUP_ONLY_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝗚𝗿𝗼𝘂𝗽𝘀!';
const botAdmin = process.env.BOT_ADMIN_MSG || '𝗜 𝗻𝗲𝗲𝗱 𝗔𝗱𝗺𝗶𝗻 𝗽𝗿𝗲𝘃𝗶𝗹𝗲𝗱𝗴𝗲𝘀!';
const NotOwner = process.env.NOT_OWNER_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝘁𝗵𝗲 ΛĿĿƐИ!';
const mycode = process.env.CODE || '254';
const port = process.env.PORT || 8080;
const databaseUrl = process.env.DATABASE_URL || '';

module.exports = {
  session,
  sessionName,
  author,
  packname,
  dev,
  owner,
  bad,
  group,
  NotOwner,
  botname,
  botAdmin,
  admin,
  mycode,
  herokuapi,
  port,
  appname,
  databaseUrl
};
