
// if you're using pannel carefully edit this part.

const sessionName = 'session';
const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR0NOYWlKOEJTOUdLLzQ1VkZQWXBBMjB6MS9CdEh5bFpjQW01UUlVTWgwND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT09XeUJaaUFuRVlwbU9HeGdZZTdBbXArY1dtRW5PWlZMSHlncXNYSjl4Zz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJXR0pYeFZRd1hOY1FFV0YwL2ZqcjF4d04vbHRLdjlLYWpSakJJK0JNVEZjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJyajgrOE9LY1RkaXhhcHJTYkM3Tnl4d0ovTklQRytIdjgzSXBkRmdxRlJFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlFFemF1ekdCMHNMV3cvYjUxbmtsU1RZdjNFN05ScjQzUXUzZk9RRVZFMVU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjNGbEx5RW5uSUI2ZHZkLzE3bUhtbTBmbWUwdDFwTWFjQWVtejVSLzNxMDg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUNMK1BCYkxUZWxLdlo1NnA0SEJmZWcwb3pNSDF4UmtIbFVFdkhEKzVtTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR1A5UjRzejhFK2pJVXNaNkxxQWFkNVdGMXRNQzduQ0liTVZjL1htaHRTND0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImVFVFdzcDNINW5CMGIyTmJQQWRTaS9xQndVRnVBWk5SK3FoZHhndTFZckM4cGhjVjdvaGM3YkJWVTN6RlBXYWgyT1luRWxhWEE0a1NnREpUN1F1c0N3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MzMsImFkdlNlY3JldEtleSI6IjlVZFpDakc1MlFyQWM2U25jYnZUNlBrTzJwTldYeENwSXRnS1V6WFFBOWs9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzU4NDQzMTExQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkFDRUYwMkMxM0Y0QkNFQjFDNDkyRDU1OEI0OTk4RDM2In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NjU3NzE5NDZ9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc1ODQ0MzExMUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBQzI3NzRGM0JEMDgzNkZFM0NCODkyQTk5Qjg2ODAwRCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzY1NzcxOTUxfSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3NTg0NDMxMTFAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQUM3NDQ4NEUyMjIzOTFFQThFNDE5REZCMjlCNTQ0NzMifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc2NTc3MTk1OH0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzU4NDQzMTExQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkFDRUQzNDQ0OUZEQjM2MDYzRTBDMEFFMDdFQTNGRDVCIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NjU3NzE5NTl9XSwibmV4dFByZUtleUlkIjo4MTMsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjo4MTMsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiUkFWRU5CT1QiLCJtZSI6eyJpZCI6IjI1NDc1ODQ0MzExMToyMEBzLndoYXRzYXBwLm5ldCIsImxpZCI6IjExNzQ4MDgyNzY1ODI1MDoyMEBsaWQiLCJuYW1lIjoiQWxsZW4ifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ1BDa25hY0hFSk9WL3NrR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6InQxTno0Vm83QkU0b0daTHZ2M3lXK1ZSbCs5Wnp5K0k0ZUVkL1NwUytGMkk9IiwiYWNjb3VudFNpZ25hdHVyZSI6Ik1QNUUrSjFKWDVpeVNuTjViY2haM3JGV056RGg5SmQrMEdHUkZ1T3drN0RPZ010ZzRrbTJvQ1VEVWM4ZE5zQ0k4UVczWlQ5VmhObVdQSjZmTlc4WEJBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJCRFRUMWVnLy8yMDZlZEExcVFGRkxEUzgwWTVWRUZKSU9ia2V6Sm1KU3VYeFBMQ2g0dFJOS3RNLzVUWXgvVFk0NVI4Uk1ENURPY3dybGlDUHFOYU5EUT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDc1ODQ0MzExMToyMEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJiZFRjK0ZhT3dST0tCbVM3Nzk4bHZsVVpmdldjOHZpT0hoSGYwcVV2aGRpIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQVVJRFFnQyJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NjU3NzE5MzksImxhc3RQcm9wSGFzaCI6IjJWNzdxVSIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBRXpQIn0=';
const appname = process.env.APP_NAME || '.';
const herokuapi = process.env.HEROKU_API;
const botname = process.env.BOTNAME || '𝗥𝗔𝗩𝗘𝗡-𝗕𝗢𝗧';
const author = process.env.STICKER_AUTHOR || 'MŦΛṖƐĿĪ ᎳᎪ ᏦᎯᎽᎾℒℰ';
const packname = process.env.STICKER_PACKNAME || 'ΛĿĿƐИ';
const dev = process.env.DEV || '254758443111';
const owner = dev.split(",");
const bad = process.env.BAD_WORD || 'fuck,umbwa,kuma,pussy,slut,bitch,cock,stupid';
const admin = process.env.ADMIN_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗿𝗲𝘀𝗲𝗿𝘃𝗲𝗱 𝗳𝗼𝗿 𝗔𝗱𝗺𝗶𝗻𝘀!';
const group = process.env.GROUP_ONLY_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝗚𝗿𝗼𝘂𝗽𝘀!';
const botAdmin = process.env.BOT_ADMIN_MSG || '𝗜 𝗻𝗲𝗲𝗱 𝗔𝗱𝗺𝗶𝗻 𝗽𝗿𝗲𝘃𝗶𝗹𝗲𝗱𝗴𝗲𝘀!';
const NotOwner = process.env.NOT_OWNER_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝘁𝗵𝗲 ΛĿĿƐИ!';
const mycode = process.env.CODE || '254';
const port = process.env.PORT || 8080;
const databaseUrl = process.env.DATABASE_URL || '';

module.exports = {
  session,
  sessionName,
  author,
  packname,
  dev,
  owner,
  bad,
  group,
  NotOwner,
  botname,
  botAdmin,
  admin,
  mycode,
  herokuapi,
  port,
  appname,
  databaseUrl
};
